################################################################################
# WARNING: automatically generated by makemake, DO NOT CHANGE!                 #
# version: 246755254ca3c70f51fa52d00538519760f8ab2e                            #
################################################################################

# ------------------------------------------------------------------------------
# GIT
# ------------------------------------------------------------------------------

git_dirty := $(shell git status -s)

git-clean-check:
ifneq ($(git_dirty),)
	git diff
	@echo "Git repository is dirty!"
	@false
endif

# ------------------------------------------------------------------------------
# GO - TESTS
# ------------------------------------------------------------------------------

.PHONY: go-test-all
go-test-all: go-test go-test-race

.PHONY: go-test
go-test:
	@go test ./...

.PHONY: go-test-race
go-test-race:
	@go test -race ./...

# ------------------------------------------------------------------------------
# GO - LINTERS
# ------------------------------------------------------------------------------

.PHONY: go-lint-all
go-lint-all: go-fmt go-vet go-mod-tidy go-errcheck go-lint

.PHONY: go-fmt
go-fmt:
        @output=$$(go fmt ./...); \
        echo $$output; \
        test -z "$${output}"

.PHONY: go-vet
go-vet:
	@go vet ./...

.PHONY: go-mod-tidy
go-mod-tidy:
	@go mod tidy

.PHONY: go-errcheck
go-errcheck:
	@errcheck ./...

.PHONY: go-lint
go-lint:
	@golint -set_exit_status ./...

# TODO(kenji): Include this target in go-lint-all once every repo can pass the check.
.PHONY: go-staticcheck
go-staticcheck:
	@gostaticcheck ./...

# ------------------------------------------------------------------------------
# Buf rules
# ------------------------------------------------------------------------------

buf-generate-all: buf-generate-base buf-generate-ts

.PHONY: buf-mod-update
buf-mod-update:
	buf mod update

.PHONY: buf-generate-base
buf-generate-base: buf-mod-update
	buf generate

.PHONY: buf-generate-ts
buf-generate-ts: buf-mod-update
ifneq (,$(wildcard ./buf.gen.ts.yaml))
	buf generate --template buf.gen.ts.yaml --include-imports --include-wkt
endif

.PHONY: typescript-compile
typescript-compile: buf-generate-ts
ifneq (,$(wildcard ./buf.gen.ts.yaml))
	tsc --skipLibCheck
endif

buf-lint:
	buf lint
