{{- if .Values.nim.ngcApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: ngc-secret
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "inference-manager-engine.generatedImagePullSecret" .}}

---

apiVersion: v1
kind: Secret
metadata:
  name: ngc-api
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
type: Opaque
data:
  NGC_API_KEY: {{ .Values.nim.ngcApiKey | b64enc }}
{{- end -}}
