{{- if .Values.enableServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inference-manager-engine.fullname" . }}-runtime
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: runtime
  endpoints:
  - port: runtime
{{- end }}
