apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-manager-server.fullname" . }}
  labels:
    {{- include "inference-manager-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inference-manager-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inference-manager-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "inference-manager-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: inference-manager-server
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
          protocol: TCP
        - name: grpc
          containerPort: {{ .Values.grpcPort }}
          protocol: TCP
        - name: ws-grpc
          containerPort: {{ .Values.workerServiceGrpcPort }}
          protocol: TCP
        - name: internal-grpc
          containerPort: {{ .Values.internalGrpcPort }}
          protocol: TCP
        - name: monitoring
          containerPort: {{ .Values.monitoringPort }}
          protocol: TCP
        - name: admin
          containerPort: {{ .Values.adminPort }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        {{- if .Values.workerServiceTls.enable }}
        - name: tls
          mountPath: /var/run/tls
          readOnly: true
        {{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "inference-manager-server.fullname" . }}
      {{- if .Values.workerServiceTls.enable }}
      - name: tls
        secret:
          secretName: {{ .Values.workerServiceTls.secretName }}
      {{- end }}
