apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "inference-manager-server.fullname" . }}
  labels:
    {{- include "inference-manager-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
