// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: api/v1/inference_server.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChatCompletionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO(kenji): Revisit this.
	Messages         []*CreateChatCompletionRequest_Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Model            string                                      `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	FrequencyPenalty float64                                     `protobuf:"fixed64,3,opt,name=frequency_penalty,json=frequencyPenalty,proto3" json:"frequency_penalty,omitempty"`
	LogitBias        map[string]float64                          `protobuf:"bytes,4,rep,name=logit_bias,json=logitBias,proto3" json:"logit_bias,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Logprobs         bool                                        `protobuf:"varint,5,opt,name=logprobs,proto3" json:"logprobs,omitempty"`
	TopLogprobs      int32                                       `protobuf:"varint,6,opt,name=top_logprobs,json=topLogprobs,proto3" json:"top_logprobs,omitempty"`
	MaxTokens        int32                                       `protobuf:"varint,7,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	N                int32                                       `protobuf:"varint,8,opt,name=n,proto3" json:"n,omitempty"`
	PresencePenalty  float64                                     `protobuf:"fixed64,9,opt,name=presence_penalty,json=presencePenalty,proto3" json:"presence_penalty,omitempty"`
	ResponseFormat   *CreateChatCompletionRequest_ResponseFormat `protobuf:"bytes,10,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	Seed             int32                                       `protobuf:"varint,11,opt,name=seed,proto3" json:"seed,omitempty"`
	// string / arrary/ null
	Stop        []string                            `protobuf:"bytes,12,rep,name=stop,proto3" json:"stop,omitempty"`
	Stream      bool                                `protobuf:"varint,13,opt,name=stream,proto3" json:"stream,omitempty"`
	Temperature float64                             `protobuf:"fixed64,14,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP        float64                             `protobuf:"fixed64,15,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	Tools       []*CreateChatCompletionRequest_Tool `protobuf:"bytes,16,rep,name=tools,proto3" json:"tools,omitempty"`
	// string or object
	ToolChocise bool   `protobuf:"varint,17,opt,name=tool_chocise,json=toolChocise,proto3" json:"tool_chocise,omitempty"`
	User        string `protobuf:"bytes,18,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateChatCompletionRequest) Reset() {
	*x = CreateChatCompletionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest) ProtoMessage() {}

func (x *CreateChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatCompletionRequest) GetMessages() []*CreateChatCompletionRequest_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateChatCompletionRequest) GetFrequencyPenalty() float64 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetLogitBias() map[string]float64 {
	if x != nil {
		return x.LogitBias
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetLogprobs() bool {
	if x != nil {
		return x.Logprobs
	}
	return false
}

func (x *CreateChatCompletionRequest) GetTopLogprobs() int32 {
	if x != nil {
		return x.TopLogprobs
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetPresencePenalty() float64 {
	if x != nil {
		return x.PresencePenalty
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetResponseFormat() *CreateChatCompletionRequest_ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *CreateChatCompletionRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetTools() []*CreateChatCompletionRequest_Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetToolChocise() bool {
	if x != nil {
		return x.ToolChocise
	}
	return false
}

func (x *CreateChatCompletionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ChatCompletion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Choices           []*ChatCompletion_Choice `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	Created           int32                    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model             string                   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemFingerprint string                   `protobuf:"bytes,5,opt,name=system_fingerprint,json=systemFingerprint,proto3" json:"system_fingerprint,omitempty"`
	Object            string                   `protobuf:"bytes,6,opt,name=object,proto3" json:"object,omitempty"`
	Usage             *ChatCompletion_Usage    `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *ChatCompletion) Reset() {
	*x = ChatCompletion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion) ProtoMessage() {}

func (x *ChatCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion.ProtoReflect.Descriptor instead.
func (*ChatCompletion) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1}
}

func (x *ChatCompletion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletion) GetChoices() []*ChatCompletion_Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletion) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletion) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletion) GetSystemFingerprint() string {
	if x != nil {
		return x.SystemFingerprint
	}
	return ""
}

func (x *ChatCompletion) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletion) GetUsage() *ChatCompletion_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// Message has fields for system message, user message, assistant message, and tool message.
type CreateChatCompletionRequest_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of content varies. For eample, it is string or array for UserMesasge.
	Content   string                                          `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Role      string                                          `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Name      string                                          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ToolCalls []*CreateChatCompletionRequest_Message_ToolCall `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
}

func (x *CreateChatCompletionRequest_Message) Reset() {
	*x = CreateChatCompletionRequest_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Message) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Message.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Message) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateChatCompletionRequest_Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message) GetToolCalls() []*CreateChatCompletionRequest_Message_ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type CreateChatCompletionRequest_ResponseFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CreateChatCompletionRequest_ResponseFormat) Reset() {
	*x = CreateChatCompletionRequest_ResponseFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_ResponseFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_ResponseFormat) ProtoMessage() {}

func (x *CreateChatCompletionRequest_ResponseFormat) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_ResponseFormat.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_ResponseFormat) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateChatCompletionRequest_ResponseFormat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateChatCompletionRequest_Tool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string                                     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function *CreateChatCompletionRequest_Tool_Function `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *CreateChatCompletionRequest_Tool) Reset() {
	*x = CreateChatCompletionRequest_Tool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Tool) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Tool) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Tool.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Tool) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CreateChatCompletionRequest_Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChatCompletionRequest_Tool) GetFunction() *CreateChatCompletionRequest_Tool_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateChatCompletionRequest_Message_ToolCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string                                                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function *CreateChatCompletionRequest_Message_ToolCall_Function `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *CreateChatCompletionRequest_Message_ToolCall) Reset() {
	*x = CreateChatCompletionRequest_Message_ToolCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Message_ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Message_ToolCall) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Message_ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Message_ToolCall.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Message_ToolCall) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CreateChatCompletionRequest_Message_ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message_ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message_ToolCall) GetFunction() *CreateChatCompletionRequest_Message_ToolCall_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateChatCompletionRequest_Message_ToolCall_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) Reset() {
	*x = CreateChatCompletionRequest_Message_ToolCall_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Message_ToolCall_Function) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Message_ToolCall_Function.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Message_ToolCall_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type CreateChatCompletionRequest_Tool_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// TODO(kenji): Revisit this. This specifies parameters the functions accepts,
	// described as a JSON Schema object.
	Parameters string `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *CreateChatCompletionRequest_Tool_Function) Reset() {
	*x = CreateChatCompletionRequest_Tool_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Tool_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Tool_Function) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Tool_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Tool_Function.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Tool_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *CreateChatCompletionRequest_Tool_Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateChatCompletionRequest_Tool_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatCompletionRequest_Tool_Function) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type ChatCompletion_Choice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinishReason string                          `protobuf:"bytes,1,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Index        int32                           `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Message      *ChatCompletion_Choice_Message  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Logprobs     *ChatCompletion_Choice_Logprobs `protobuf:"bytes,4,opt,name=logprobs,proto3" json:"logprobs,omitempty"`
}

func (x *ChatCompletion_Choice) Reset() {
	*x = ChatCompletion_Choice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice) ProtoMessage() {}

func (x *ChatCompletion_Choice) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ChatCompletion_Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatCompletion_Choice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletion_Choice) GetMessage() *ChatCompletion_Choice_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatCompletion_Choice) GetLogprobs() *ChatCompletion_Choice_Logprobs {
	if x != nil {
		return x.Logprobs
	}
	return nil
}

type ChatCompletion_Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompletionTokens int32 `protobuf:"varint,1,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	PromptTokens     int32 `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	TotalTokens      int32 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
}

func (x *ChatCompletion_Usage) Reset() {
	*x = ChatCompletion_Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Usage) ProtoMessage() {}

func (x *ChatCompletion_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Usage.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Usage) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ChatCompletion_Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ChatCompletion_Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ChatCompletion_Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ChatCompletion_Choice_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string                                    `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls []*ChatCompletion_Choice_Message_ToolCall `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Role      string                                    `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *ChatCompletion_Choice_Message) Reset() {
	*x = ChatCompletion_Choice_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice_Message) ProtoMessage() {}

func (x *ChatCompletion_Choice_Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice_Message.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice_Message) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ChatCompletion_Choice_Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatCompletion_Choice_Message) GetToolCalls() []*ChatCompletion_Choice_Message_ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatCompletion_Choice_Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ChatCompletion_Choice_Logprobs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []*ChatCompletion_Choice_Logprobs_Content `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatCompletion_Choice_Logprobs) Reset() {
	*x = ChatCompletion_Choice_Logprobs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice_Logprobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice_Logprobs) ProtoMessage() {}

func (x *ChatCompletion_Choice_Logprobs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice_Logprobs.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice_Logprobs) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *ChatCompletion_Choice_Logprobs) GetContent() []*ChatCompletion_Choice_Logprobs_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type ChatCompletion_Choice_Message_ToolCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string                                           `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function *ChatCompletion_Choice_Message_ToolCall_Function `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *ChatCompletion_Choice_Message_ToolCall) Reset() {
	*x = ChatCompletion_Choice_Message_ToolCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice_Message_ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice_Message_ToolCall) ProtoMessage() {}

func (x *ChatCompletion_Choice_Message_ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice_Message_ToolCall.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice_Message_ToolCall) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

func (x *ChatCompletion_Choice_Message_ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletion_Choice_Message_ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatCompletion_Choice_Message_ToolCall) GetFunction() *ChatCompletion_Choice_Message_ToolCall_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type ChatCompletion_Choice_Message_ToolCall_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *ChatCompletion_Choice_Message_ToolCall_Function) Reset() {
	*x = ChatCompletion_Choice_Message_ToolCall_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice_Message_ToolCall_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice_Message_ToolCall_Function) ProtoMessage() {}

func (x *ChatCompletion_Choice_Message_ToolCall_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice_Message_ToolCall_Function.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice_Message_ToolCall_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0, 0, 0, 0}
}

func (x *ChatCompletion_Choice_Message_ToolCall_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatCompletion_Choice_Message_ToolCall_Function) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ChatCompletion_Choice_Logprobs_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Logprob float64 `protobuf:"fixed64,2,opt,name=logprob,proto3" json:"logprob,omitempty"`
	// A list of integers representing the UTF-8 bytes representation of the token.
	Bytes       []byte                                              `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	TopLogprobs *ChatCompletion_Choice_Logprobs_Content_TopLogprobs `protobuf:"bytes,4,opt,name=top_logprobs,json=topLogprobs,proto3" json:"top_logprobs,omitempty"`
}

func (x *ChatCompletion_Choice_Logprobs_Content) Reset() {
	*x = ChatCompletion_Choice_Logprobs_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice_Logprobs_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice_Logprobs_Content) ProtoMessage() {}

func (x *ChatCompletion_Choice_Logprobs_Content) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice_Logprobs_Content.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice_Logprobs_Content) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0, 1, 0}
}

func (x *ChatCompletion_Choice_Logprobs_Content) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChatCompletion_Choice_Logprobs_Content) GetLogprob() float64 {
	if x != nil {
		return x.Logprob
	}
	return 0
}

func (x *ChatCompletion_Choice_Logprobs_Content) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *ChatCompletion_Choice_Logprobs_Content) GetTopLogprobs() *ChatCompletion_Choice_Logprobs_Content_TopLogprobs {
	if x != nil {
		return x.TopLogprobs
	}
	return nil
}

type ChatCompletion_Choice_Logprobs_Content_TopLogprobs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Logprob float64 `protobuf:"fixed64,2,opt,name=logprob,proto3" json:"logprob,omitempty"`
	Bytes   []byte  `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *ChatCompletion_Choice_Logprobs_Content_TopLogprobs) Reset() {
	*x = ChatCompletion_Choice_Logprobs_Content_TopLogprobs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice_Logprobs_Content_TopLogprobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice_Logprobs_Content_TopLogprobs) ProtoMessage() {}

func (x *ChatCompletion_Choice_Logprobs_Content_TopLogprobs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice_Logprobs_Content_TopLogprobs.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice_Logprobs_Content_TopLogprobs) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0, 1, 0, 0}
}

func (x *ChatCompletion_Choice_Logprobs_Content_TopLogprobs) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChatCompletion_Choice_Logprobs_Content_TopLogprobs) GetLogprob() float64 {
	if x != nil {
		return x.Logprob
	}
	return 0
}

func (x *ChatCompletion_Choice_Logprobs_Content_TopLogprobs) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_api_v1_inference_server_proto protoreflect.FileDescriptor

var file_api_v1_inference_server_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1a, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x0c, 0x0a, 0x1b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5b, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x6c, 0x6c,
	0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2b, 0x0a, 0x11,
	0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x79, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x65, 0x0a, 0x0a, 0x6c, 0x6f, 0x67,
	0x69, 0x74, 0x5f, 0x62, 0x69, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e,
	0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x74, 0x42, 0x69, 0x61, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x74, 0x42, 0x69, 0x61, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x6f, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x46, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x6f, 0x70, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x5f, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x6f, 0x70, 0x50, 0x12,
	0x52, 0x0a, 0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c,
	0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x74, 0x6f,
	0x6f, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x68, 0x6f, 0x63,
	0x69, 0x73, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x74, 0x6f, 0x6f, 0x6c, 0x43,
	0x68, 0x6f, 0x63, 0x69, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x92, 0x03, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x67, 0x0a, 0x0a, 0x74, 0x6f, 0x6f, 0x6c,
	0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x48, 0x2e, 0x6c,
	0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x6f,
	0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c,
	0x73, 0x1a, 0xdb, 0x01, 0x0a, 0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x6d, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x51, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x3c, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a,
	0x24, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xdf, 0x01, 0x0a, 0x04, 0x54, 0x6f, 0x6f, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x61, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x6f,
	0x6f, 0x6c, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x60, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x74,
	0x42, 0x69, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x97, 0x0b, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4b, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07, 0x63, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f,
	0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x46, 0x0a, 0x05,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6c, 0x6c,
	0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x75,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0xea, 0x07, 0x0a, 0x06, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x53, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6c, 0x6c,
	0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x56, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x3a, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x52, 0x08, 0x6c,
	0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x1a, 0xf2, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x61, 0x0a,
	0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x42, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x6f, 0x6f,
	0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x1a, 0xd5, 0x01, 0x0a, 0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x67, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3c,
	0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x82, 0x03, 0x0a,
	0x08, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x12, 0x5c, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x6c, 0x6c, 0x6d,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x97, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67,
	0x70, 0x72, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x70,
	0x72, 0x6f, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x71, 0x0a, 0x0c, 0x74, 0x6f, 0x70,
	0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x4e, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x70, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x52,
	0x0b, 0x74, 0x6f, 0x70, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x1a, 0x53, 0x0a, 0x0b,
	0x54, 0x6f, 0x70, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x1a, 0x7c, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x32,
	0x0d, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x32,
	0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6c, 0x6d,
	0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_inference_server_proto_rawDescOnce sync.Once
	file_api_v1_inference_server_proto_rawDescData = file_api_v1_inference_server_proto_rawDesc
)

func file_api_v1_inference_server_proto_rawDescGZIP() []byte {
	file_api_v1_inference_server_proto_rawDescOnce.Do(func() {
		file_api_v1_inference_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_inference_server_proto_rawDescData)
	})
	return file_api_v1_inference_server_proto_rawDescData
}

var file_api_v1_inference_server_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_v1_inference_server_proto_goTypes = []interface{}{
	(*CreateChatCompletionRequest)(nil),                           // 0: llmoperator.chat.server.v1.CreateChatCompletionRequest
	(*ChatCompletion)(nil),                                        // 1: llmoperator.chat.server.v1.ChatCompletion
	(*CreateChatCompletionRequest_Message)(nil),                   // 2: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message
	(*CreateChatCompletionRequest_ResponseFormat)(nil),            // 3: llmoperator.chat.server.v1.CreateChatCompletionRequest.ResponseFormat
	(*CreateChatCompletionRequest_Tool)(nil),                      // 4: llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool
	nil,                                                           // 5: llmoperator.chat.server.v1.CreateChatCompletionRequest.LogitBiasEntry
	(*CreateChatCompletionRequest_Message_ToolCall)(nil),          // 6: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall
	(*CreateChatCompletionRequest_Message_ToolCall_Function)(nil), // 7: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall.Function
	(*CreateChatCompletionRequest_Tool_Function)(nil),             // 8: llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool.Function
	(*ChatCompletion_Choice)(nil),                                 // 9: llmoperator.chat.server.v1.ChatCompletion.Choice
	(*ChatCompletion_Usage)(nil),                                  // 10: llmoperator.chat.server.v1.ChatCompletion.Usage
	(*ChatCompletion_Choice_Message)(nil),                         // 11: llmoperator.chat.server.v1.ChatCompletion.Choice.Message
	(*ChatCompletion_Choice_Logprobs)(nil),                        // 12: llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs
	(*ChatCompletion_Choice_Message_ToolCall)(nil),                // 13: llmoperator.chat.server.v1.ChatCompletion.Choice.Message.ToolCall
	(*ChatCompletion_Choice_Message_ToolCall_Function)(nil),       // 14: llmoperator.chat.server.v1.ChatCompletion.Choice.Message.ToolCall.Function
	(*ChatCompletion_Choice_Logprobs_Content)(nil),                // 15: llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs.Content
	(*ChatCompletion_Choice_Logprobs_Content_TopLogprobs)(nil),    // 16: llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs.Content.TopLogprobs
}
var file_api_v1_inference_server_proto_depIdxs = []int32{
	2,  // 0: llmoperator.chat.server.v1.CreateChatCompletionRequest.messages:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Message
	5,  // 1: llmoperator.chat.server.v1.CreateChatCompletionRequest.logit_bias:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.LogitBiasEntry
	3,  // 2: llmoperator.chat.server.v1.CreateChatCompletionRequest.response_format:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.ResponseFormat
	4,  // 3: llmoperator.chat.server.v1.CreateChatCompletionRequest.tools:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool
	9,  // 4: llmoperator.chat.server.v1.ChatCompletion.choices:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice
	10, // 5: llmoperator.chat.server.v1.ChatCompletion.usage:type_name -> llmoperator.chat.server.v1.ChatCompletion.Usage
	6,  // 6: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.tool_calls:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall
	8,  // 7: llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool.function:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool.Function
	7,  // 8: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall.function:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall.Function
	11, // 9: llmoperator.chat.server.v1.ChatCompletion.Choice.message:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice.Message
	12, // 10: llmoperator.chat.server.v1.ChatCompletion.Choice.logprobs:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs
	13, // 11: llmoperator.chat.server.v1.ChatCompletion.Choice.Message.tool_calls:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice.Message.ToolCall
	15, // 12: llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs.content:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs.Content
	14, // 13: llmoperator.chat.server.v1.ChatCompletion.Choice.Message.ToolCall.function:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice.Message.ToolCall.Function
	16, // 14: llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs.Content.top_logprobs:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice.Logprobs.Content.TopLogprobs
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_v1_inference_server_proto_init() }
func file_api_v1_inference_server_proto_init() {
	if File_api_v1_inference_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_inference_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_ResponseFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Tool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Message_ToolCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Message_ToolCall_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Tool_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice_Logprobs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice_Message_ToolCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice_Message_ToolCall_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice_Logprobs_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice_Logprobs_Content_TopLogprobs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_inference_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_inference_server_proto_goTypes,
		DependencyIndexes: file_api_v1_inference_server_proto_depIdxs,
		MessageInfos:      file_api_v1_inference_server_proto_msgTypes,
	}.Build()
	File_api_v1_inference_server_proto = out.File
	file_api_v1_inference_server_proto_rawDesc = nil
	file_api_v1_inference_server_proto_goTypes = nil
	file_api_v1_inference_server_proto_depIdxs = nil
}
