// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InferenceEngineInternalServiceClient is the client API for InferenceEngineInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceEngineInternalServiceClient interface {
	RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*RegisterModelResponse, error)
}

type inferenceEngineInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceEngineInternalServiceClient(cc grpc.ClientConnInterface) InferenceEngineInternalServiceClient {
	return &inferenceEngineInternalServiceClient{cc}
}

func (c *inferenceEngineInternalServiceClient) RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*RegisterModelResponse, error) {
	out := new(RegisterModelResponse)
	err := c.cc.Invoke(ctx, "/llmoperator.inference_engine.v1.InferenceEngineInternalService/RegisterModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceEngineInternalServiceServer is the server API for InferenceEngineInternalService service.
// All implementations must embed UnimplementedInferenceEngineInternalServiceServer
// for forward compatibility
type InferenceEngineInternalServiceServer interface {
	RegisterModel(context.Context, *RegisterModelRequest) (*RegisterModelResponse, error)
	mustEmbedUnimplementedInferenceEngineInternalServiceServer()
}

// UnimplementedInferenceEngineInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInferenceEngineInternalServiceServer struct {
}

func (UnimplementedInferenceEngineInternalServiceServer) RegisterModel(context.Context, *RegisterModelRequest) (*RegisterModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterModel not implemented")
}
func (UnimplementedInferenceEngineInternalServiceServer) mustEmbedUnimplementedInferenceEngineInternalServiceServer() {
}

// UnsafeInferenceEngineInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceEngineInternalServiceServer will
// result in compilation errors.
type UnsafeInferenceEngineInternalServiceServer interface {
	mustEmbedUnimplementedInferenceEngineInternalServiceServer()
}

func RegisterInferenceEngineInternalServiceServer(s grpc.ServiceRegistrar, srv InferenceEngineInternalServiceServer) {
	s.RegisterService(&InferenceEngineInternalService_ServiceDesc, srv)
}

func _InferenceEngineInternalService_RegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineInternalServiceServer).RegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmoperator.inference_engine.v1.InferenceEngineInternalService/RegisterModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineInternalServiceServer).RegisterModel(ctx, req.(*RegisterModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceEngineInternalService_ServiceDesc is the grpc.ServiceDesc for InferenceEngineInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceEngineInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmoperator.inference_engine.v1.InferenceEngineInternalService",
	HandlerType: (*InferenceEngineInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModel",
			Handler:    _InferenceEngineInternalService_RegisterModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/inference_engine.proto",
}
