// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/inference_server_internal.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceInternalService_ProcessTasksInternal_FullMethodName = "/llmariner.inference.server.v1.InferenceInternalService/ProcessTasksInternal"
)

// InferenceInternalServiceClient is the client API for InferenceInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceInternalServiceClient interface {
	ProcessTasksInternal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessTasksInternalRequest, ProcessTasksInternalResponse], error)
}

type inferenceInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceInternalServiceClient(cc grpc.ClientConnInterface) InferenceInternalServiceClient {
	return &inferenceInternalServiceClient{cc}
}

func (c *inferenceInternalServiceClient) ProcessTasksInternal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessTasksInternalRequest, ProcessTasksInternalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceInternalService_ServiceDesc.Streams[0], InferenceInternalService_ProcessTasksInternal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessTasksInternalRequest, ProcessTasksInternalResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceInternalService_ProcessTasksInternalClient = grpc.BidiStreamingClient[ProcessTasksInternalRequest, ProcessTasksInternalResponse]

// InferenceInternalServiceServer is the server API for InferenceInternalService service.
// All implementations must embed UnimplementedInferenceInternalServiceServer
// for forward compatibility.
type InferenceInternalServiceServer interface {
	ProcessTasksInternal(grpc.BidiStreamingServer[ProcessTasksInternalRequest, ProcessTasksInternalResponse]) error
	mustEmbedUnimplementedInferenceInternalServiceServer()
}

// UnimplementedInferenceInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceInternalServiceServer struct{}

func (UnimplementedInferenceInternalServiceServer) ProcessTasksInternal(grpc.BidiStreamingServer[ProcessTasksInternalRequest, ProcessTasksInternalResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessTasksInternal not implemented")
}
func (UnimplementedInferenceInternalServiceServer) mustEmbedUnimplementedInferenceInternalServiceServer() {
}
func (UnimplementedInferenceInternalServiceServer) testEmbeddedByValue() {}

// UnsafeInferenceInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceInternalServiceServer will
// result in compilation errors.
type UnsafeInferenceInternalServiceServer interface {
	mustEmbedUnimplementedInferenceInternalServiceServer()
}

func RegisterInferenceInternalServiceServer(s grpc.ServiceRegistrar, srv InferenceInternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedInferenceInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceInternalService_ServiceDesc, srv)
}

func _InferenceInternalService_ProcessTasksInternal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceInternalServiceServer).ProcessTasksInternal(&grpc.GenericServerStream[ProcessTasksInternalRequest, ProcessTasksInternalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceInternalService_ProcessTasksInternalServer = grpc.BidiStreamingServer[ProcessTasksInternalRequest, ProcessTasksInternalResponse]

// InferenceInternalService_ServiceDesc is the grpc.ServiceDesc for InferenceInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.inference.server.v1.InferenceInternalService",
	HandlerType: (*InferenceInternalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessTasksInternal",
			Handler:       _InferenceInternalService_ProcessTasksInternal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/inference_server_internal.proto",
}
