// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: api/v1/inference_server.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChatCompletionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO(kenji): Revisit this.
	Messages         []*CreateChatCompletionRequest_Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Model            string                                      `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	FrequencyPenalty float64                                     `protobuf:"fixed64,3,opt,name=frequency_penalty,json=frequencyPenalty,proto3" json:"frequency_penalty,omitempty"`
	LogitBias        map[string]float64                          `protobuf:"bytes,4,rep,name=logit_bias,json=logitBias,proto3" json:"logit_bias,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Logprobs         bool                                        `protobuf:"varint,5,opt,name=logprobs,proto3" json:"logprobs,omitempty"`
	TopLogprobs      int32                                       `protobuf:"varint,6,opt,name=top_logprobs,json=topLogprobs,proto3" json:"top_logprobs,omitempty"`
	MaxTokens        int32                                       `protobuf:"varint,7,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	N                int32                                       `protobuf:"varint,8,opt,name=n,proto3" json:"n,omitempty"`
	PresencePenalty  float64                                     `protobuf:"fixed64,9,opt,name=presence_penalty,json=presencePenalty,proto3" json:"presence_penalty,omitempty"`
	ResponseFormat   *CreateChatCompletionRequest_ResponseFormat `protobuf:"bytes,10,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	Seed             int32                                       `protobuf:"varint,11,opt,name=seed,proto3" json:"seed,omitempty"`
	// string / arrary/ null
	Stop        []string                                `protobuf:"bytes,12,rep,name=stop,proto3" json:"stop,omitempty"`
	Stream      bool                                    `protobuf:"varint,13,opt,name=stream,proto3" json:"stream,omitempty"`
	Temperature float64                                 `protobuf:"fixed64,14,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP        float64                                 `protobuf:"fixed64,15,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	Tools       []*CreateChatCompletionRequest_Tool     `protobuf:"bytes,16,rep,name=tools,proto3" json:"tools,omitempty"`
	ToolChoice  *CreateChatCompletionRequest_ToolChoice `protobuf:"bytes,17,opt,name=tool_choice,json=toolChoice,proto3" json:"tool_choice,omitempty"`
	User        string                                  `protobuf:"bytes,18,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateChatCompletionRequest) Reset() {
	*x = CreateChatCompletionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest) ProtoMessage() {}

func (x *CreateChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatCompletionRequest) GetMessages() []*CreateChatCompletionRequest_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateChatCompletionRequest) GetFrequencyPenalty() float64 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetLogitBias() map[string]float64 {
	if x != nil {
		return x.LogitBias
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetLogprobs() bool {
	if x != nil {
		return x.Logprobs
	}
	return false
}

func (x *CreateChatCompletionRequest) GetTopLogprobs() int32 {
	if x != nil {
		return x.TopLogprobs
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetPresencePenalty() float64 {
	if x != nil {
		return x.PresencePenalty
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetResponseFormat() *CreateChatCompletionRequest_ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *CreateChatCompletionRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *CreateChatCompletionRequest) GetTools() []*CreateChatCompletionRequest_Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetToolChoice() *CreateChatCompletionRequest_ToolChoice {
	if x != nil {
		return x.ToolChoice
	}
	return nil
}

func (x *CreateChatCompletionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ToolCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function *ToolCall_Function `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *ToolCall_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type Logprobs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []*Logprobs_Content `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
}

func (x *Logprobs) Reset() {
	*x = Logprobs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logprobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logprobs) ProtoMessage() {}

func (x *Logprobs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logprobs.ProtoReflect.Descriptor instead.
func (*Logprobs) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{2}
}

func (x *Logprobs) GetContent() []*Logprobs_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompletionTokens int32 `protobuf:"varint,1,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	PromptTokens     int32 `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	TotalTokens      int32 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
}

func (x *Usage) Reset() {
	*x = Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ChatCompletion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Choices           []*ChatCompletion_Choice `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	Created           int32                    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model             string                   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemFingerprint string                   `protobuf:"bytes,5,opt,name=system_fingerprint,json=systemFingerprint,proto3" json:"system_fingerprint,omitempty"`
	Object            string                   `protobuf:"bytes,6,opt,name=object,proto3" json:"object,omitempty"`
	Usage             *Usage                   `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *ChatCompletion) Reset() {
	*x = ChatCompletion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion) ProtoMessage() {}

func (x *ChatCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion.ProtoReflect.Descriptor instead.
func (*ChatCompletion) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{4}
}

func (x *ChatCompletion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletion) GetChoices() []*ChatCompletion_Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletion) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletion) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletion) GetSystemFingerprint() string {
	if x != nil {
		return x.SystemFingerprint
	}
	return ""
}

func (x *ChatCompletion) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletion) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ChatCompletionChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Choices           []*ChatCompletionChunk_Choice `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	Created           int32                         `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model             string                        `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemFingerprint string                        `protobuf:"bytes,5,opt,name=system_fingerprint,json=systemFingerprint,proto3" json:"system_fingerprint,omitempty"`
	Object            string                        `protobuf:"bytes,6,opt,name=object,proto3" json:"object,omitempty"`
	Usage             *Usage                        `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *ChatCompletionChunk) Reset() {
	*x = ChatCompletionChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk) ProtoMessage() {}

func (x *ChatCompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{5}
}

func (x *ChatCompletionChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionChunk) GetChoices() []*ChatCompletionChunk_Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionChunk) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionChunk) GetSystemFingerprint() string {
	if x != nil {
		return x.SystemFingerprint
	}
	return ""
}

func (x *ChatCompletionChunk) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// RagFunction is used to unmarshal the json string specified in `Parameters` of Tool message.
type RagFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorStoreName string `protobuf:"bytes,1,opt,name=vector_store_name,json=vectorStoreName,proto3" json:"vector_store_name,omitempty"`
}

func (x *RagFunction) Reset() {
	*x = RagFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RagFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagFunction) ProtoMessage() {}

func (x *RagFunction) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagFunction.ProtoReflect.Descriptor instead.
func (*RagFunction) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{6}
}

func (x *RagFunction) GetVectorStoreName() string {
	if x != nil {
		return x.VectorStoreName
	}
	return ""
}

// Message has fields for system message, user message, assistant message, and tool message.
type CreateChatCompletionRequest_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of content varies. For eample, it is string or array for UserMesasge.
	Content   string                                          `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Role      string                                          `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Name      string                                          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ToolCalls []*CreateChatCompletionRequest_Message_ToolCall `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
}

func (x *CreateChatCompletionRequest_Message) Reset() {
	*x = CreateChatCompletionRequest_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Message) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Message.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Message) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateChatCompletionRequest_Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message) GetToolCalls() []*CreateChatCompletionRequest_Message_ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type CreateChatCompletionRequest_ResponseFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CreateChatCompletionRequest_ResponseFormat) Reset() {
	*x = CreateChatCompletionRequest_ResponseFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_ResponseFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_ResponseFormat) ProtoMessage() {}

func (x *CreateChatCompletionRequest_ResponseFormat) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_ResponseFormat.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_ResponseFormat) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateChatCompletionRequest_ResponseFormat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateChatCompletionRequest_Tool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string                                     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function *CreateChatCompletionRequest_Tool_Function `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *CreateChatCompletionRequest_Tool) Reset() {
	*x = CreateChatCompletionRequest_Tool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Tool) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Tool) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Tool.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Tool) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CreateChatCompletionRequest_Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChatCompletionRequest_Tool) GetFunction() *CreateChatCompletionRequest_Tool_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateChatCompletionRequest_ToolChoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO(guangrui): revisit on how to assign string value of ToolChoice.
	Choice   string                                           `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Type     string                                           `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function *CreateChatCompletionRequest_ToolChoice_Function `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *CreateChatCompletionRequest_ToolChoice) Reset() {
	*x = CreateChatCompletionRequest_ToolChoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_ToolChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_ToolChoice) ProtoMessage() {}

func (x *CreateChatCompletionRequest_ToolChoice) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_ToolChoice.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_ToolChoice) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 3}
}

func (x *CreateChatCompletionRequest_ToolChoice) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *CreateChatCompletionRequest_ToolChoice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChatCompletionRequest_ToolChoice) GetFunction() *CreateChatCompletionRequest_ToolChoice_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateChatCompletionRequest_Message_ToolCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string                                                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function *CreateChatCompletionRequest_Message_ToolCall_Function `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *CreateChatCompletionRequest_Message_ToolCall) Reset() {
	*x = CreateChatCompletionRequest_Message_ToolCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Message_ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Message_ToolCall) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Message_ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Message_ToolCall.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Message_ToolCall) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CreateChatCompletionRequest_Message_ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message_ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message_ToolCall) GetFunction() *CreateChatCompletionRequest_Message_ToolCall_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateChatCompletionRequest_Message_ToolCall_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) Reset() {
	*x = CreateChatCompletionRequest_Message_ToolCall_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Message_ToolCall_Function) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Message_ToolCall_Function.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Message_ToolCall_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatCompletionRequest_Message_ToolCall_Function) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type CreateChatCompletionRequest_Tool_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// TODO(kenji): Revisit this. This specifies parameters the functions accepts,
	// described as a JSON Schema object.
	Parameters string `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *CreateChatCompletionRequest_Tool_Function) Reset() {
	*x = CreateChatCompletionRequest_Tool_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_Tool_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_Tool_Function) ProtoMessage() {}

func (x *CreateChatCompletionRequest_Tool_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_Tool_Function.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_Tool_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *CreateChatCompletionRequest_Tool_Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateChatCompletionRequest_Tool_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatCompletionRequest_Tool_Function) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type CreateChatCompletionRequest_ToolChoice_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateChatCompletionRequest_ToolChoice_Function) Reset() {
	*x = CreateChatCompletionRequest_ToolChoice_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatCompletionRequest_ToolChoice_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatCompletionRequest_ToolChoice_Function) ProtoMessage() {}

func (x *CreateChatCompletionRequest_ToolChoice_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatCompletionRequest_ToolChoice_Function.ProtoReflect.Descriptor instead.
func (*CreateChatCompletionRequest_ToolChoice_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *CreateChatCompletionRequest_ToolChoice_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ToolCall_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *ToolCall_Function) Reset() {
	*x = ToolCall_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolCall_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall_Function) ProtoMessage() {}

func (x *ToolCall_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall_Function.ProtoReflect.Descriptor instead.
func (*ToolCall_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ToolCall_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall_Function) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type Logprobs_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Logprob float64 `protobuf:"fixed64,2,opt,name=logprob,proto3" json:"logprob,omitempty"`
	// A list of integers representing the UTF-8 bytes representation of the token.
	Bytes       []byte                        `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	TopLogprobs *Logprobs_Content_TopLogprobs `protobuf:"bytes,4,opt,name=top_logprobs,json=topLogprobs,proto3" json:"top_logprobs,omitempty"`
}

func (x *Logprobs_Content) Reset() {
	*x = Logprobs_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logprobs_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logprobs_Content) ProtoMessage() {}

func (x *Logprobs_Content) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logprobs_Content.ProtoReflect.Descriptor instead.
func (*Logprobs_Content) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Logprobs_Content) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Logprobs_Content) GetLogprob() float64 {
	if x != nil {
		return x.Logprob
	}
	return 0
}

func (x *Logprobs_Content) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Logprobs_Content) GetTopLogprobs() *Logprobs_Content_TopLogprobs {
	if x != nil {
		return x.TopLogprobs
	}
	return nil
}

type Logprobs_Content_TopLogprobs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Logprob float64 `protobuf:"fixed64,2,opt,name=logprob,proto3" json:"logprob,omitempty"`
	Bytes   []byte  `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *Logprobs_Content_TopLogprobs) Reset() {
	*x = Logprobs_Content_TopLogprobs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logprobs_Content_TopLogprobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logprobs_Content_TopLogprobs) ProtoMessage() {}

func (x *Logprobs_Content_TopLogprobs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logprobs_Content_TopLogprobs.ProtoReflect.Descriptor instead.
func (*Logprobs_Content_TopLogprobs) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Logprobs_Content_TopLogprobs) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Logprobs_Content_TopLogprobs) GetLogprob() float64 {
	if x != nil {
		return x.Logprob
	}
	return 0
}

func (x *Logprobs_Content_TopLogprobs) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type ChatCompletion_Choice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinishReason string                         `protobuf:"bytes,1,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Index        int32                          `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Message      *ChatCompletion_Choice_Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Logprobs     *Logprobs                      `protobuf:"bytes,4,opt,name=logprobs,proto3" json:"logprobs,omitempty"`
}

func (x *ChatCompletion_Choice) Reset() {
	*x = ChatCompletion_Choice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice) ProtoMessage() {}

func (x *ChatCompletion_Choice) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ChatCompletion_Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatCompletion_Choice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletion_Choice) GetMessage() *ChatCompletion_Choice_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatCompletion_Choice) GetLogprobs() *Logprobs {
	if x != nil {
		return x.Logprobs
	}
	return nil
}

type ChatCompletion_Choice_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string      `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls []*ToolCall `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Role      string      `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *ChatCompletion_Choice_Message) Reset() {
	*x = ChatCompletion_Choice_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletion_Choice_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletion_Choice_Message) ProtoMessage() {}

func (x *ChatCompletion_Choice_Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletion_Choice_Message.ProtoReflect.Descriptor instead.
func (*ChatCompletion_Choice_Message) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *ChatCompletion_Choice_Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatCompletion_Choice_Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatCompletion_Choice_Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ChatCompletionChunk_Choice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delta        *ChatCompletionChunk_Choice_Delta `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	FinishReason string                            `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Index        int32                             `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Logprobs     *Logprobs                         `protobuf:"bytes,4,opt,name=logprobs,proto3" json:"logprobs,omitempty"`
}

func (x *ChatCompletionChunk_Choice) Reset() {
	*x = ChatCompletionChunk_Choice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletionChunk_Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk_Choice) ProtoMessage() {}

func (x *ChatCompletionChunk_Choice) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk_Choice.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk_Choice) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ChatCompletionChunk_Choice) GetDelta() *ChatCompletionChunk_Choice_Delta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ChatCompletionChunk_Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatCompletionChunk_Choice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletionChunk_Choice) GetLogprobs() *Logprobs {
	if x != nil {
		return x.Logprobs
	}
	return nil
}

type ChatCompletionChunk_Choice_Delta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string                                       `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls []*ChatCompletionChunk_Choice_Delta_ToolCall `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Role      string                                       `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *ChatCompletionChunk_Choice_Delta) Reset() {
	*x = ChatCompletionChunk_Choice_Delta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletionChunk_Choice_Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk_Choice_Delta) ProtoMessage() {}

func (x *ChatCompletionChunk_Choice_Delta) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk_Choice_Delta.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk_Choice_Delta) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *ChatCompletionChunk_Choice_Delta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatCompletionChunk_Choice_Delta) GetToolCalls() []*ChatCompletionChunk_Choice_Delta_ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatCompletionChunk_Choice_Delta) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ChatCompletionChunk_Choice_Delta_ToolCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string                                              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function *ChatCompletionChunk_Choice_Delta_ToolCall_Function `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall) Reset() {
	*x = ChatCompletionChunk_Choice_Delta_ToolCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk_Choice_Delta_ToolCall) ProtoMessage() {}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk_Choice_Delta_ToolCall.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk_Choice_Delta_ToolCall) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{5, 0, 0, 0}
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall) GetFunction() *ChatCompletionChunk_Choice_Delta_ToolCall_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type ChatCompletionChunk_Choice_Delta_ToolCall_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall_Function) Reset() {
	*x = ChatCompletionChunk_Choice_Delta_ToolCall_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk_Choice_Delta_ToolCall_Function) ProtoMessage() {}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall_Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk_Choice_Delta_ToolCall_Function.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk_Choice_Delta_ToolCall_Function) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_proto_rawDescGZIP(), []int{5, 0, 0, 0, 0}
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatCompletionChunk_Choice_Delta_ToolCall_Function) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

var File_api_v1_inference_server_proto protoreflect.FileDescriptor

var file_api_v1_inference_server_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1a, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x0e, 0x0a, 0x1b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5b, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x6c, 0x6c,
	0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2b, 0x0a, 0x11,
	0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x79, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x65, 0x0a, 0x0a, 0x6c, 0x6f, 0x67,
	0x69, 0x74, 0x5f, 0x62, 0x69, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e,
	0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x74, 0x42, 0x69, 0x61, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x74, 0x42, 0x69, 0x61, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x6f, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x46, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x6f, 0x70, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x5f, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x6f, 0x70, 0x50, 0x12,
	0x52, 0x0a, 0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c,
	0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x74, 0x6f,
	0x6f, 0x6c, 0x73, 0x12, 0x63, 0x0a, 0x0b, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x0a, 0x74, 0x6f,
	0x6f, 0x6c, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x92, 0x03, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x67, 0x0a, 0x0a, 0x74, 0x6f,
	0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x48,
	0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x43, 0x61,
	0x6c, 0x6c, 0x73, 0x1a, 0xdb, 0x01, 0x0a, 0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x6d, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x51, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x3c, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x1a, 0x24, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xdf, 0x01, 0x0a, 0x04, 0x54, 0x6f, 0x6f, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x61, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x54, 0x6f, 0x6f, 0x6c, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x60, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0xc1, 0x01, 0x0a, 0x0a, 0x54, 0x6f,
	0x6f, 0x6c, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x67, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1e, 0x0a,
	0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x3c, 0x0a,
	0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x74, 0x42, 0x69, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb7, 0x01, 0x0a, 0x08,
	0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x49, 0x0a, 0x08,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6f, 0x6c,
	0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3c, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xd6, 0x02, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f,
	0x62, 0x73, 0x12, 0x46, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x81, 0x02, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6c,
	0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x5b, 0x0a, 0x0c,
	0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x54, 0x6f, 0x70, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x52, 0x0b, 0x74, 0x6f,
	0x70, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x1a, 0x53, 0x0a, 0x0b, 0x54, 0x6f, 0x70,
	0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x07, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x7c,
	0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0xf8, 0x04, 0x0a,
	0x0e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x4b, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x6f,
	0x69, 0x63, 0x65, 0x52, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2d, 0x0a, 0x12,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x37, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x1a, 0xd8, 0x02, 0x0a,
	0x06, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x53, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72,
	0x6f, 0x62, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x52,
	0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x1a, 0x7c, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x43,
	0x0a, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x43, 0x61,
	0x6c, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0xfc, 0x06, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x50, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x36, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x66, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x37, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0xd2, 0x04, 0x0a, 0x06, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x05,
	0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6c, 0x6c,
	0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x43, 0x68, 0x6f,
	0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61,
	0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x40, 0x0a, 0x08, 0x6c,
	0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x70, 0x72,
	0x6f, 0x62, 0x73, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x62, 0x73, 0x1a, 0xf6, 0x02,
	0x0a, 0x05, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x64, 0x0a, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x74, 0x61, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x09, 0x74, 0x6f,
	0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x1a, 0xd8, 0x01, 0x0a, 0x08,
	0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x6a, 0x0a, 0x08,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4e,
	0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x2e,
	0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x54, 0x6f, 0x6f,
	0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3c, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x0b, 0x52, 0x61, 0x67, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x32, 0x0d, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x6c, 0x6d, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_inference_server_proto_rawDescOnce sync.Once
	file_api_v1_inference_server_proto_rawDescData = file_api_v1_inference_server_proto_rawDesc
)

func file_api_v1_inference_server_proto_rawDescGZIP() []byte {
	file_api_v1_inference_server_proto_rawDescOnce.Do(func() {
		file_api_v1_inference_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_inference_server_proto_rawDescData)
	})
	return file_api_v1_inference_server_proto_rawDescData
}

var file_api_v1_inference_server_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_v1_inference_server_proto_goTypes = []interface{}{
	(*CreateChatCompletionRequest)(nil),                // 0: llmoperator.chat.server.v1.CreateChatCompletionRequest
	(*ToolCall)(nil),                                   // 1: llmoperator.chat.server.v1.ToolCall
	(*Logprobs)(nil),                                   // 2: llmoperator.chat.server.v1.Logprobs
	(*Usage)(nil),                                      // 3: llmoperator.chat.server.v1.Usage
	(*ChatCompletion)(nil),                             // 4: llmoperator.chat.server.v1.ChatCompletion
	(*ChatCompletionChunk)(nil),                        // 5: llmoperator.chat.server.v1.ChatCompletionChunk
	(*RagFunction)(nil),                                // 6: llmoperator.chat.server.v1.RagFunction
	(*CreateChatCompletionRequest_Message)(nil),        // 7: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message
	(*CreateChatCompletionRequest_ResponseFormat)(nil), // 8: llmoperator.chat.server.v1.CreateChatCompletionRequest.ResponseFormat
	(*CreateChatCompletionRequest_Tool)(nil),           // 9: llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool
	(*CreateChatCompletionRequest_ToolChoice)(nil),     // 10: llmoperator.chat.server.v1.CreateChatCompletionRequest.ToolChoice
	nil, // 11: llmoperator.chat.server.v1.CreateChatCompletionRequest.LogitBiasEntry
	(*CreateChatCompletionRequest_Message_ToolCall)(nil),          // 12: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall
	(*CreateChatCompletionRequest_Message_ToolCall_Function)(nil), // 13: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall.Function
	(*CreateChatCompletionRequest_Tool_Function)(nil),             // 14: llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool.Function
	(*CreateChatCompletionRequest_ToolChoice_Function)(nil),       // 15: llmoperator.chat.server.v1.CreateChatCompletionRequest.ToolChoice.Function
	(*ToolCall_Function)(nil),                                     // 16: llmoperator.chat.server.v1.ToolCall.Function
	(*Logprobs_Content)(nil),                                      // 17: llmoperator.chat.server.v1.Logprobs.Content
	(*Logprobs_Content_TopLogprobs)(nil),                          // 18: llmoperator.chat.server.v1.Logprobs.Content.TopLogprobs
	(*ChatCompletion_Choice)(nil),                                 // 19: llmoperator.chat.server.v1.ChatCompletion.Choice
	(*ChatCompletion_Choice_Message)(nil),                         // 20: llmoperator.chat.server.v1.ChatCompletion.Choice.Message
	(*ChatCompletionChunk_Choice)(nil),                            // 21: llmoperator.chat.server.v1.ChatCompletionChunk.Choice
	(*ChatCompletionChunk_Choice_Delta)(nil),                      // 22: llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta
	(*ChatCompletionChunk_Choice_Delta_ToolCall)(nil),             // 23: llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta.ToolCall
	(*ChatCompletionChunk_Choice_Delta_ToolCall_Function)(nil),    // 24: llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta.ToolCall.Function
}
var file_api_v1_inference_server_proto_depIdxs = []int32{
	7,  // 0: llmoperator.chat.server.v1.CreateChatCompletionRequest.messages:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Message
	11, // 1: llmoperator.chat.server.v1.CreateChatCompletionRequest.logit_bias:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.LogitBiasEntry
	8,  // 2: llmoperator.chat.server.v1.CreateChatCompletionRequest.response_format:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.ResponseFormat
	9,  // 3: llmoperator.chat.server.v1.CreateChatCompletionRequest.tools:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool
	10, // 4: llmoperator.chat.server.v1.CreateChatCompletionRequest.tool_choice:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.ToolChoice
	16, // 5: llmoperator.chat.server.v1.ToolCall.function:type_name -> llmoperator.chat.server.v1.ToolCall.Function
	17, // 6: llmoperator.chat.server.v1.Logprobs.content:type_name -> llmoperator.chat.server.v1.Logprobs.Content
	19, // 7: llmoperator.chat.server.v1.ChatCompletion.choices:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice
	3,  // 8: llmoperator.chat.server.v1.ChatCompletion.usage:type_name -> llmoperator.chat.server.v1.Usage
	21, // 9: llmoperator.chat.server.v1.ChatCompletionChunk.choices:type_name -> llmoperator.chat.server.v1.ChatCompletionChunk.Choice
	3,  // 10: llmoperator.chat.server.v1.ChatCompletionChunk.usage:type_name -> llmoperator.chat.server.v1.Usage
	12, // 11: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.tool_calls:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall
	14, // 12: llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool.function:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Tool.Function
	15, // 13: llmoperator.chat.server.v1.CreateChatCompletionRequest.ToolChoice.function:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.ToolChoice.Function
	13, // 14: llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall.function:type_name -> llmoperator.chat.server.v1.CreateChatCompletionRequest.Message.ToolCall.Function
	18, // 15: llmoperator.chat.server.v1.Logprobs.Content.top_logprobs:type_name -> llmoperator.chat.server.v1.Logprobs.Content.TopLogprobs
	20, // 16: llmoperator.chat.server.v1.ChatCompletion.Choice.message:type_name -> llmoperator.chat.server.v1.ChatCompletion.Choice.Message
	2,  // 17: llmoperator.chat.server.v1.ChatCompletion.Choice.logprobs:type_name -> llmoperator.chat.server.v1.Logprobs
	1,  // 18: llmoperator.chat.server.v1.ChatCompletion.Choice.Message.tool_calls:type_name -> llmoperator.chat.server.v1.ToolCall
	22, // 19: llmoperator.chat.server.v1.ChatCompletionChunk.Choice.delta:type_name -> llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta
	2,  // 20: llmoperator.chat.server.v1.ChatCompletionChunk.Choice.logprobs:type_name -> llmoperator.chat.server.v1.Logprobs
	23, // 21: llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta.tool_calls:type_name -> llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta.ToolCall
	24, // 22: llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta.ToolCall.function:type_name -> llmoperator.chat.server.v1.ChatCompletionChunk.Choice.Delta.ToolCall.Function
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_v1_inference_server_proto_init() }
func file_api_v1_inference_server_proto_init() {
	if File_api_v1_inference_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_inference_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Logprobs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletionChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RagFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_ResponseFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Tool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_ToolChoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Message_ToolCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Message_ToolCall_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_Tool_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatCompletionRequest_ToolChoice_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolCall_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Logprobs_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Logprobs_Content_TopLogprobs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletion_Choice_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletionChunk_Choice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletionChunk_Choice_Delta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletionChunk_Choice_Delta_ToolCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCompletionChunk_Choice_Delta_ToolCall_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_inference_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_inference_server_proto_goTypes,
		DependencyIndexes: file_api_v1_inference_server_proto_depIdxs,
		MessageInfos:      file_api_v1_inference_server_proto_msgTypes,
	}.Build()
	File_api_v1_inference_server_proto = out.File
	file_api_v1_inference_server_proto_rawDesc = nil
	file_api_v1_inference_server_proto_goTypes = nil
	file_api_v1_inference_server_proto_depIdxs = nil
}
