// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: api/v1/inference_server_embeddings.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEmbeddingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This can be a string or an array of strings, but we use string assuming that it is more common.
	Input          string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Model          string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	EncodingFormat string `protobuf:"bytes,3,opt,name=encoding_format,json=encodingFormat,proto3" json:"encoding_format,omitempty"`
	Dimensions     int32  `protobuf:"varint,4,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	User           string `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateEmbeddingRequest) Reset() {
	*x = CreateEmbeddingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_embeddings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmbeddingRequest) ProtoMessage() {}

func (x *CreateEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_embeddings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*CreateEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_embeddings_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEmbeddingRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *CreateEmbeddingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateEmbeddingRequest) GetEncodingFormat() string {
	if x != nil {
		return x.EncodingFormat
	}
	return ""
}

func (x *CreateEmbeddingRequest) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *CreateEmbeddingRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type Embedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int32     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Embedding []float64 `protobuf:"fixed64,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Object    string    `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_embeddings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_embeddings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_embeddings_proto_rawDescGZIP(), []int{1}
}

func (x *Embedding) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Embedding) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Embedding) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

var File_api_v1_inference_server_embeddings_proto protoreflect.FileDescriptor

var file_api_v1_inference_server_embeddings_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x6c, 0x6c, 0x6d, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x57,
	0x0a, 0x09, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6c, 0x6d, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2d, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_v1_inference_server_embeddings_proto_rawDescOnce sync.Once
	file_api_v1_inference_server_embeddings_proto_rawDescData = file_api_v1_inference_server_embeddings_proto_rawDesc
)

func file_api_v1_inference_server_embeddings_proto_rawDescGZIP() []byte {
	file_api_v1_inference_server_embeddings_proto_rawDescOnce.Do(func() {
		file_api_v1_inference_server_embeddings_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_inference_server_embeddings_proto_rawDescData)
	})
	return file_api_v1_inference_server_embeddings_proto_rawDescData
}

var file_api_v1_inference_server_embeddings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_inference_server_embeddings_proto_goTypes = []interface{}{
	(*CreateEmbeddingRequest)(nil), // 0: llmoperator.embeddings.server.v1.CreateEmbeddingRequest
	(*Embedding)(nil),              // 1: llmoperator.embeddings.server.v1.Embedding
}
var file_api_v1_inference_server_embeddings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_inference_server_embeddings_proto_init() }
func file_api_v1_inference_server_embeddings_proto_init() {
	if File_api_v1_inference_server_embeddings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_inference_server_embeddings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmbeddingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_embeddings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Embedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_inference_server_embeddings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_inference_server_embeddings_proto_goTypes,
		DependencyIndexes: file_api_v1_inference_server_embeddings_proto_depIdxs,
		MessageInfos:      file_api_v1_inference_server_embeddings_proto_msgTypes,
	}.Build()
	File_api_v1_inference_server_embeddings_proto = out.File
	file_api_v1_inference_server_embeddings_proto_rawDesc = nil
	file_api_v1_inference_server_embeddings_proto_goTypes = nil
	file_api_v1_inference_server_embeddings_proto_depIdxs = nil
}
