// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: api/v1/inference_server_worker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EngineStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EngineId string   `protobuf:"bytes,1,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	ModelIds []string `protobuf:"bytes,2,rep,name=model_ids,json=modelIds,proto3" json:"model_ids,omitempty"`
}

func (x *EngineStatus) Reset() {
	*x = EngineStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EngineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStatus) ProtoMessage() {}

func (x *EngineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStatus.ProtoReflect.Descriptor instead.
func (*EngineStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_worker_proto_rawDescGZIP(), []int{0}
}

func (x *EngineStatus) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *EngineStatus) GetModelIds() []string {
	if x != nil {
		return x.ModelIds
	}
	return nil
}

type ProcessTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ProcessTasksRequest_EngineStatus
	Message isProcessTasksRequest_Message `protobuf_oneof:"message"`
}

func (x *ProcessTasksRequest) Reset() {
	*x = ProcessTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTasksRequest) ProtoMessage() {}

func (x *ProcessTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTasksRequest.ProtoReflect.Descriptor instead.
func (*ProcessTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_worker_proto_rawDescGZIP(), []int{1}
}

func (m *ProcessTasksRequest) GetMessage() isProcessTasksRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ProcessTasksRequest) GetEngineStatus() *EngineStatus {
	if x, ok := x.GetMessage().(*ProcessTasksRequest_EngineStatus); ok {
		return x.EngineStatus
	}
	return nil
}

type isProcessTasksRequest_Message interface {
	isProcessTasksRequest_Message()
}

type ProcessTasksRequest_EngineStatus struct {
	EngineStatus *EngineStatus `protobuf:"bytes,1,opt,name=engine_status,json=engineStatus,proto3,oneof"` // TODO(kenji): Add task result.
}

func (*ProcessTasksRequest_EngineStatus) isProcessTasksRequest_Message() {}

type ProcessTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessTasksResponse) Reset() {
	*x = ProcessTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_server_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTasksResponse) ProtoMessage() {}

func (x *ProcessTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_server_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTasksResponse.ProtoReflect.Descriptor instead.
func (*ProcessTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_server_worker_proto_rawDescGZIP(), []int{2}
}

var File_api_v1_inference_server_worker_proto protoreflect.FileDescriptor

var file_api_v1_inference_server_worker_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x73,
	0x22, 0x76, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x0d, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x69, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52,
	0x0c, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x9c, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x0c,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x34, 0x2e, 0x6c,
	0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x35, 0x2e, 0x6c, 0x6c, 0x6d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6c,
	0x6d, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_inference_server_worker_proto_rawDescOnce sync.Once
	file_api_v1_inference_server_worker_proto_rawDescData = file_api_v1_inference_server_worker_proto_rawDesc
)

func file_api_v1_inference_server_worker_proto_rawDescGZIP() []byte {
	file_api_v1_inference_server_worker_proto_rawDescOnce.Do(func() {
		file_api_v1_inference_server_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_inference_server_worker_proto_rawDescData)
	})
	return file_api_v1_inference_server_worker_proto_rawDescData
}

var file_api_v1_inference_server_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_inference_server_worker_proto_goTypes = []interface{}{
	(*EngineStatus)(nil),         // 0: llmoperator.inference.server.v1.EngineStatus
	(*ProcessTasksRequest)(nil),  // 1: llmoperator.inference.server.v1.ProcessTasksRequest
	(*ProcessTasksResponse)(nil), // 2: llmoperator.inference.server.v1.ProcessTasksResponse
}
var file_api_v1_inference_server_worker_proto_depIdxs = []int32{
	0, // 0: llmoperator.inference.server.v1.ProcessTasksRequest.engine_status:type_name -> llmoperator.inference.server.v1.EngineStatus
	1, // 1: llmoperator.inference.server.v1.InferenceWorkerService.ProcessTasks:input_type -> llmoperator.inference.server.v1.ProcessTasksRequest
	2, // 2: llmoperator.inference.server.v1.InferenceWorkerService.ProcessTasks:output_type -> llmoperator.inference.server.v1.ProcessTasksResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_inference_server_worker_proto_init() }
func file_api_v1_inference_server_worker_proto_init() {
	if File_api_v1_inference_server_worker_proto != nil {
		return
	}
	file_api_v1_inference_server_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_inference_server_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EngineStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_server_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_inference_server_worker_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ProcessTasksRequest_EngineStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_inference_server_worker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_inference_server_worker_proto_goTypes,
		DependencyIndexes: file_api_v1_inference_server_worker_proto_depIdxs,
		MessageInfos:      file_api_v1_inference_server_worker_proto_msgTypes,
	}.Build()
	File_api_v1_inference_server_worker_proto = out.File
	file_api_v1_inference_server_worker_proto_rawDesc = nil
	file_api_v1_inference_server_worker_proto_goTypes = nil
	file_api_v1_inference_server_worker_proto_depIdxs = nil
}
