// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InferenceServiceClient is the client API for InferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceServiceClient interface {
	GetInferenceStatus(ctx context.Context, in *GetInferenceStatusRequest, opts ...grpc.CallOption) (*InferenceStatus, error)
	ActivateModel(ctx context.Context, in *ActivateModelRequest, opts ...grpc.CallOption) (*ActivateModelResponse, error)
	DeactivateModel(ctx context.Context, in *DeactivateModelRequest, opts ...grpc.CallOption) (*DeactivateModelResponse, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) GetInferenceStatus(ctx context.Context, in *GetInferenceStatusRequest, opts ...grpc.CallOption) (*InferenceStatus, error) {
	out := new(InferenceStatus)
	err := c.cc.Invoke(ctx, "/llmariner.inference.server.v1.InferenceService/GetInferenceStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) ActivateModel(ctx context.Context, in *ActivateModelRequest, opts ...grpc.CallOption) (*ActivateModelResponse, error) {
	out := new(ActivateModelResponse)
	err := c.cc.Invoke(ctx, "/llmariner.inference.server.v1.InferenceService/ActivateModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) DeactivateModel(ctx context.Context, in *DeactivateModelRequest, opts ...grpc.CallOption) (*DeactivateModelResponse, error) {
	out := new(DeactivateModelResponse)
	err := c.cc.Invoke(ctx, "/llmariner.inference.server.v1.InferenceService/DeactivateModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServiceServer is the server API for InferenceService service.
// All implementations must embed UnimplementedInferenceServiceServer
// for forward compatibility
type InferenceServiceServer interface {
	GetInferenceStatus(context.Context, *GetInferenceStatusRequest) (*InferenceStatus, error)
	ActivateModel(context.Context, *ActivateModelRequest) (*ActivateModelResponse, error)
	DeactivateModel(context.Context, *DeactivateModelRequest) (*DeactivateModelResponse, error)
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInferenceServiceServer struct {
}

func (UnimplementedInferenceServiceServer) GetInferenceStatus(context.Context, *GetInferenceStatusRequest) (*InferenceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInferenceStatus not implemented")
}
func (UnimplementedInferenceServiceServer) ActivateModel(context.Context, *ActivateModelRequest) (*ActivateModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateModel not implemented")
}
func (UnimplementedInferenceServiceServer) DeactivateModel(context.Context, *DeactivateModelRequest) (*DeactivateModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateModel not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceServer will
// result in compilation errors.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_GetInferenceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInferenceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).GetInferenceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.inference.server.v1.InferenceService/GetInferenceStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).GetInferenceStatus(ctx, req.(*GetInferenceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ActivateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ActivateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.inference.server.v1.InferenceService/ActivateModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ActivateModel(ctx, req.(*ActivateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_DeactivateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).DeactivateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.inference.server.v1.InferenceService/DeactivateModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).DeactivateModel(ctx, req.(*DeactivateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.inference.server.v1.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInferenceStatus",
			Handler:    _InferenceService_GetInferenceStatus_Handler,
		},
		{
			MethodName: "ActivateModel",
			Handler:    _InferenceService_ActivateModel_Handler,
		},
		{
			MethodName: "DeactivateModel",
			Handler:    _InferenceService_DeactivateModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/inference_server_management.proto",
}
