// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/inference_server_worker.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceWorkerService_ProcessTasks_FullMethodName = "/llmariner.inference.server.v1.InferenceWorkerService/ProcessTasks"
)

// InferenceWorkerServiceClient is the client API for InferenceWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceWorkerServiceClient interface {
	ProcessTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessTasksRequest, ProcessTasksResponse], error)
}

type inferenceWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceWorkerServiceClient(cc grpc.ClientConnInterface) InferenceWorkerServiceClient {
	return &inferenceWorkerServiceClient{cc}
}

func (c *inferenceWorkerServiceClient) ProcessTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessTasksRequest, ProcessTasksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceWorkerService_ServiceDesc.Streams[0], InferenceWorkerService_ProcessTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessTasksRequest, ProcessTasksResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceWorkerService_ProcessTasksClient = grpc.BidiStreamingClient[ProcessTasksRequest, ProcessTasksResponse]

// InferenceWorkerServiceServer is the server API for InferenceWorkerService service.
// All implementations must embed UnimplementedInferenceWorkerServiceServer
// for forward compatibility.
type InferenceWorkerServiceServer interface {
	ProcessTasks(grpc.BidiStreamingServer[ProcessTasksRequest, ProcessTasksResponse]) error
	mustEmbedUnimplementedInferenceWorkerServiceServer()
}

// UnimplementedInferenceWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceWorkerServiceServer struct{}

func (UnimplementedInferenceWorkerServiceServer) ProcessTasks(grpc.BidiStreamingServer[ProcessTasksRequest, ProcessTasksResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessTasks not implemented")
}
func (UnimplementedInferenceWorkerServiceServer) mustEmbedUnimplementedInferenceWorkerServiceServer() {
}
func (UnimplementedInferenceWorkerServiceServer) testEmbeddedByValue() {}

// UnsafeInferenceWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceWorkerServiceServer will
// result in compilation errors.
type UnsafeInferenceWorkerServiceServer interface {
	mustEmbedUnimplementedInferenceWorkerServiceServer()
}

func RegisterInferenceWorkerServiceServer(s grpc.ServiceRegistrar, srv InferenceWorkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedInferenceWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceWorkerService_ServiceDesc, srv)
}

func _InferenceWorkerService_ProcessTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceWorkerServiceServer).ProcessTasks(&grpc.GenericServerStream[ProcessTasksRequest, ProcessTasksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceWorkerService_ProcessTasksServer = grpc.BidiStreamingServer[ProcessTasksRequest, ProcessTasksResponse]

// InferenceWorkerService_ServiceDesc is the grpc.ServiceDesc for InferenceWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.inference.server.v1.InferenceWorkerService",
	HandlerType: (*InferenceWorkerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessTasks",
			Handler:       _InferenceWorkerService_ProcessTasks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/inference_server_worker.proto",
}
