name: manual-create-pull-request
on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "OPTIONAL: new version (e.g., 0.23.1) (default: bump minor version)"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ github.event.inputs.custom_tag }}
        default_bump: minor
        dry_run: true
    - name: Update versions
      run: ./hack/update-chart-version.sh ${{ steps.tag_version.outputs.new_version }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Release ${{ steps.tag_version.outputs.new_tag }}
        commit-message: Release ${{ steps.tag_version.outputs.new_tag }}
        add-paths: deployments/*/Chart.yaml
        branch: release-${{ steps.tag_version.outputs.new_tag }}
        reviewers: ${{ github.actor }}
        body: This pull-request is created by `manual workflow` by ${{ github.actor }}
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        labels: skip-changelog
